### ISSUE TITLE
Alter styles

### ISSUE THREAD

**Issue by MochaPenguin** [MochaPenguin/mochapenguin.github.io#4]
It would be nice to be able to alter the styles used across the blog. And add new styles in css files.

SCSS is being transformed to CSS somehow during site-generation.

i.e. override base styles to have styles like these:
```css
body {
  font-size: 100%;
}

h1 {
  color: black;
  font-size: 1.3em;
}

h2 {
  color: #d02e83;
  font-size: 1.2em;
}

h3 {
  color: blue;
  font-size: 1.1em;
}

h4 {
  color: green;
  font-size: 1.0em;
}

p {
  font-family: "Arial", Helvetica, sans-serif;
  font-size: medium;
}
```
